### PR TITLE
Rescript 11 (WIP)

### PR DESCRIPTION
**Pull request by mvaled**
This PR shows that we can upgrade to the upcoming release of rescript.

We could even remove the only dev dependency; but it's not required.

### CODE REVIEW

**Comment by mvaled** [comment]
Hi @TheSpyder 

I only created this PR because at first [it gave me some issues](https://github.com/rescript-lang/rescript-compiler/pull/6249#issuecomment-1632016141).

Indeed, I'm not sure either if webapi benefits from the new things in Rescript 11.  But it's good to know that it works with it; provided you set your project to `"uncurried": false`.

In the future, however, we might want to update it to adopt the new uncurried standard, so that projects be not required to set this flag.  Otherwise, we might cause friction between the language and the library.

**Comment by TheSpyder** [comment]
I'm happy to add uncurried false to the bsconfig here, that's not a problem.

Support for uncurried mode is no simple task for this library. Some of the changes I'd like to do will make that easier, but it's a lot of work.

**Comment by mvaled** [comment]
I'm not sure if that would work, i.e a project with `"uncurried": true` depending on a project that has it set to `false`.   I could test this idea.

**Comment by TheSpyder** [comment]
I haven't tried either, but one of my other projects also depends on `false` - and parts of it actually don't work with `false` at the moment (I mentioned this to the devs but haven't logged a ticket for it yet).

**Comment by TheSpyder** [comment]
0.9.0 has been published, and I believe it works with uncurried mode thanks to #123

**Pull request closed without merging**
